### PR TITLE
Show outdated packages links if exist

### LINKED ISSUE #13: Show outdated packages links
Some outdated packages are sub-dependencies of composer project.

In this cases, show them on the result.

Go up to the root dependencies (packages defined directly on `composer.json` file).

Note: To help, take a look to `composer depends` command.

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Closes #13.

- [x] Show outdated packages links
- [x] Manage BC for `VersionsCheck` class constructor
- [x] If possible, make it available as an option
- [x] Update `README.md`
- [ ] Update gif demo
- [x] Fix / Add tests

ping @EmanueleMinotto

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
I don't know if I should enabled colored output for depends command.

With colors:

versions_check_colors_yes

Without colors:

versions_check_colors_no

What do you think?

I prefer colored one, but don't know if it's confusing even if I added blank lines between packages for clearest output.

**Comment by EmanueleMinotto** [comment]
I prefer the colored output too, a possible fix could be using the bold for root-level dependencies

**Comment by Soullivaneuh** [comment]
> could be using the bold for root-level dependencies

Didn't know for bold. Does composer have a special output tag for this?

**Comment by EmanueleMinotto** [comment]
Composer console is based on `symfony/console`, so [this](http://symfony.com/doc/current/components/console/introduction.html#coloring-the-output) (the small `OutputFormatterStyle` example) should be valid for composer too (not verified yet).

**Comment by Soullivaneuh** [comment]
I don't really like bold option because it does not follow Composer output styling:

versions_check_colors_bold

**Comment by EmanueleMinotto** [comment]
wow, yes it's completely different from my expectations! :\
than I'm in favour of a not colored solution, because those should be considered secondary information 

anyway attention because there's a problem in that screenshot, quoting https://getcomposer.org/doc/articles/versions.md#tilde :
> ~1.2 is equivalent to >=1.2 <2.0.0

**Comment by Soullivaneuh** [comment]
Yeah, but what is the problem about `~1.2` ? This is just an information of which requirement of willdurand/negotiation is set on the rest-bundle package.

That especially permits to developer to see quickly in which dependencies the version is out of date.

**Comment by EmanueleMinotto** [comment]
you're right, sorry, it's still a bit tricky for me to differentiate this approach from a "update all the things!" hehe

**Comment by Soullivaneuh** [comment]
Internal note: The plugin actually parse the global `composer.json` file for extra options. This produce random test results depending on the working environment.

Mock this part and return fixture file paths.

**Comment by Soullivaneuh** [comment]
Tests broken, see https://github.com/composer/composer/issues/4643.

**Comment by Soullivaneuh** [comment]
I finally by passed the depends command usage which is the cause of the issue.

The `DependsCommandWrapper` class is not needed anymore IMO, have to remove it.

**Comment by Soullivaneuh** [comment]
@EmanueleMinotto There is the actual output:

image

What do you think?

**Comment by EmanueleMinotto** [comment]
seems great, well done! :+1:

**Comment by Soullivaneuh** [comment]
Here the new animation:

anim

**Comment by Soullivaneuh** [comment]
@EmanueleMinotto Available on [v1.1.0](https://github.com/Soullivaneuh/composer-versions-check/releases/tag/v1.1.0).

**Comment by Soullivaneuh** [comment]
@EmanueleMinotto I think I will disable it by default on next major. Sometimes it produces a very large output:

```bash
17 packages are not up to date:

  - kriswallsmith/buzz (v0.10) latest is v0.15
    Required by m4tthumphrey/php-gitlab-api (>=0.7)
    Required by gentle/bitbucket-api (0.10)

  - m4tthumphrey/php-gitlab-api (7.11.0) latest is 7.13.0
    Required by gushphp/gush (~7.11.0)

  - guzzlehttp/streams (2.1.0) latest is 3.0.0
    Required by guzzlehttp/guzzle (~2.1)

  - guzzlehttp/guzzle (4.2.3) latest is 6.2.0
    Required by alexkovalevych/jira-api (~4.0|~5.0)
    Required by guzzlehttp/progress-subscriber (~4.0)
    Required by gushphp/gush (~4.2.3)

  - jacobkiers/oauth (1.0.10) latest is 1.0.12
    Required by gentle/bitbucket-api (1.0.10)

  - gentle/bitbucket-api (0.5.2) latest is 0.8.0
    Required by gushphp/gush (~0.5.2)

  - knplabs/github-api (1.3.1) latest is 1.6.0
    Required by gushphp/gush (~1.3.1)

  - phpspec/php-diff (v1.0.2) latest is v1.1.0
    Required by phpspec/phpspec (~1.0.0)

  - phpdocumentor/reflection-docblock (2.0.4) latest is 3.0.1
    Required by phpspec/prophecy (~2.0)
    Required by sensiolabs-de/deprecation-detector (~2.0)

  - nikic/php-parser (v1.4.1) latest is v2.0.1
    Required by sensiolabs-de/deprecation-detector (^1.3)

  - justinrainbow/json-schema (1.6.1) latest is 2.0.0
    Required by herrera-io/json (>=1.0,<2.0-dev)

  - symfony/yaml (v2.8.4) latest is v3.0.4
    Required by gushphp/gush (~2.8.0)
    Required by phpspec/phpspec (~2.1|~3.0)
    Required by behat/behat (~2.1|~3.0)
    Required by phpunit/phpunit (~2.1|~3.0)

  - symfony/finder (v2.8.4) latest is v3.0.4
    Required by gushphp/gush (~2.8.0)
    Required by fabpot/php-cs-fixer (~2.1|~3.0)
    Required by sebastian/finder-facade (~2.3|~3.0)
    Required by phpspec/phpspec (~2.1|~3.0)
    Required by sensiolabs-de/deprecation-detector (^2.6 || ^3.0)

  - symfony/process (v2.8.4) latest is v3.0.4
    Required by gushphp/gush (~2.8.0)
    Required by fabpot/php-cs-fixer (~2.3|~3.0)
    Required by phpspec/phpspec (^2.6|~3.0)
    Required by jolicode/jolinotif (~2.3|~3.0)

  - symfony/event-dispatcher (v2.8.4) latest is v3.0.4
    Required by guzzle/guzzle (~2.1)
    Required by gushphp/gush (~2.8.0)
    Required by fabpot/php-cs-fixer (~2.1|~3.0)
    Required by phpspec/phpspec (~2.1|~3.0)
    Required by behat/behat (~2.1|~3.0)

  - symfony/console (v2.8.4) latest is v3.0.4
    Required by kherge/amend (~2.1)
    Required by gushphp/gush (~2.8.0)
    Required by fabpot/php-cs-fixer (~2.3|~3.0)
    Required by phpspec/phpspec (~2.3|~3.0)
    Required by behat/behat (~2.1|~3.0)
    Required by sensiolabs-de/deprecation-detector (^2.6 || ^3.0)
    Required by sebastian/phpcpd (~2.7|^3.0)

  - symfony/filesystem (v2.8.4) latest is v3.0.4
    Required by gushphp/gush (~2.8.0)
    Required by fabpot/php-cs-fixer (~2.1|~3.0)
    Required by symfony/config (~2.8|~3.0)
    Required by sensiolabs-de/deprecation-detector (^2.7 || ^3.0)
```

BTW, the `composer why-not` command will do the same work.

**Comment by EmanueleMinotto** [comment]
yes, now it seems a duplicated script 👍

**Pull request merged**
